name: smarthome
description: A new Flutter project.

version: 0.2.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  charts_flutter: ^0.9.0
  package_info: ^0.4.0+17
  flutter_linkify: ^3.1.2
  url_launcher: ^5.4.5




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
