name: smarthome

version: 0.4.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  charts_flutter: ^0.9.0
  package_info: ^0.4.0+17
  flutter_linkify: ^3.1.2
  url_launcher: ^5.4.5
  socket_io_client: ^0.9.9
  socket_io_common: ^0.9.1
  flutter_local_notifications: ^1.4.3
  flutter_iconpicker: ^1.1.3
  random_color: ^1.0.5
  local_auth: ^0.6.2+1
  dynamic_theme: ^1.0.1
  html: ^0.14.0+3
  path_provider: ^1.6.8
  esys_flutter_share: ^1.0.2
  file_picker: ^1.9.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
