name: bolio
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_staggered_grid_view: ^0.3.3
  socket_io_client: ^0.9.12
  http: ^0.12.2
  auto_size_text: ^2.1.0
  charts_flutter: ^0.9.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
